modLoader="javafml"
loaderVersion="[36,)"
logoFile="HellasWilds.png"
license="Restricted"

[[mods]]
modId="hellaswilds"
version="2.1.1"
displayName="HellasWilds"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
'''

[[dependencies.hellaswilds]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellaswilds]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellaswilds]]
modId="hellascontrol"
mandatory=true
versionRange="[2.0.0,)"
ordering="NONE"
side="BOTH"
