modLoader="javafml"
loaderVersion="${loaderVersionRange}"
logoFile="HellasWilds.png"
license="Restricted"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="${modName}"
displayURL="https://discord.pixelmon-server.com"
credits="${modAuthors}"
authors="${modAuthors}"
description='''
${modDescription}
'''

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="${forgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="${minecraftVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="hellascontrol"
mandatory=true
versionRange="[2.1.0,)"
ordering="NONE"
side="BOTH"
